version: "3"
networks:
    env-net:
        driver: bridge
services:
  mysql:
    image: mysql:5.7
    container_name: mysqlcontainer
    tty: true
    ports:
        - "4208:3306"
    volumes:
        - "/var/libclea/mysql/:/var/lib/mysql"
    environment:
        MYSQL_DATABASE: <wp_database>
        MYSQL_USER: <wp_user> 
        MYSQL_PASSWORD: <wp_pass>        
        MYSQL_ROOT_PASSWORD: <password>
    networks:
        - env-net      
  server:
      image: wordpress:latest
      container_name: wordpresscontainer
      ports:
           - "4282:80"
      volumes:
          - /var/www/html/:/var/www/html
      environment:
          WORDPRESS_DB_HOST: mysqlcontainer 
          WORDPRESS_DB_NAME: <wp_database>
          WORDPRESS_DB_USER: <wp_user>
          WORDPRESS_DB_PASSWORD: <wp_pass>
      depends_on:
          - mysqlcontainer
      networks:
          - env- net
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmincontainer
      ports:
          - "4283:80"
      environment:
          PMA_HOST: mysqlcontainer
          MYSQL_ROOT_PASSWORD: <phpma_pass>
      depends_on:
          - mysqlcontainer
      networks:
          - env-net
